# Basic configuration
language: java
dist: trusty
jdk: oraclejdk8
sudo: false

# Increase the size of the heap
#before_script:
  #- "sudo service mysql stop"
  #- "echo $JAVA_OPTS"
  #- "export JAVA_OPTS=-Xmx1024m"
  #- "git clone https://github.com/gchq/stroom-resources.git"
  #- "cd stroom-resources"
  #- "docker-compose -f hbase-kafka-mysql-stroom-zk.yml up -d"
  #- "cd .."

# We run a script to build dependencies and do database setup
#install: "./.travis.install.sh"

# We need to run shadowJar otherwise we won't be able to publish to DockerHub
script: ./gradlew clean build 

# TODO: reinstate image releases and GitHub releases

# Push to DockerHub. The username and password were added using the Travis CLI.
# The configuration below will only push an image if the branch being built is master.
#after_success:
#  - docker build --tag=gchq/stroom:latest stroom-app/.
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push gchq/stroom;
#    fi

# Push to GitHub releases - the key was generated by the Travis CLI.
#deploy:
#  provider: releases
#  api_key:
#    secure: xUPJboaSjxs3lKCqXu5zYzdV75S+lu5EZ6RD+RigmQ5MSjeuFBhoBKYaJUz+ejaoFLfF8WSUbmlgTeRMK7QI4MtCqjy08uREext8sm0behMREz4mmPEb9eTLu+WfIXFbnOPG4pKzkAtHA3x+hNQN3EWga1Xa2WXGYdOuK1B7vnrYOPo9D2zI12JCaoXt0KUQ70LwE07uwBIuDn+0EbVsAftFatJh7jZXeMsE8GmdcwsM/DObKjtTLBH3bpE8pPPJ8H0ssuIsQk2jHg91cTgrlB0q0K1a5TjeKKMGPMY6S6UR9cB7l7FqCVEsOd7T/ExdKp1TflMRyuuKG9ACBXTaegfBt7pP7KYEpYtidC5p/b1J4cYvazVTIfo6m93wnOJAdcD1XeMqNIQZVSxNuflmgM8xZz+UuqPBF4dk3Z5Eoh4sTH+t6WmZY6YoIt6tRMQ8xRyvkTfzsfYUtsV4csyeB2oy5s/GJmYGtR5GjjK6T+mh8RmI/DVWW50ubdFaAYYdz+LSgfpGhBXEBkYPghMSjYiPDsJStXsOwRSQbR9LmRO7jk08PxxT33pLr8Ct0HoQPpSP8Fom4q1ntrZBDjeHL8/2cQtRKqUg3X9G0sU7aW5i0G4U7BE42Xkcc/VVJhFrVbRj5+xQq70uMyUmHi2Wh+mBQSY+ZlBrvr6FRcKj42E=
#  file: stroom-app/build/libs/stroom-app-all.jar
#  skip_cleanup: true
#  on:
#    tags: true

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
